services:
  backend:
    image: ghcr.io/stp-team/backend/backend:latest
    container_name: backend
    ports:
      - "127.0.0.1:${API_PORT:-8000}:8000"
    restart: unless-stopped
    env_file:
      - "backend/.env"

  frontend:
    image: ghcr.io/stp-team/backend/frontend:latest
    container_name: frontend
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-5173}:5173"
    restart: unless-stopped
    depends_on:
      - backend
